config/routes.rb
Rails.application.routes.draw do
  
  get 'experiments/index'

  get '/testcenter', to: 'testcenter#index'

  get '/metafizzy', to: 'metafizzy#index'

  get '/periodictable', to: 'periodictable#index'
  
  resources :lewisdot
  root 'welcome#index'

end

app/models/element.rb
class Element

	attr_reader :name, :wiki, :group, :position, :number, :molar, :electrons, :small

	def initialize(options = {})
		@name = options[:name]
		@wiki = :wiki, :group, :position, :number, :molar, :electrons, :small
	end

end

app/models/periodic_table.rb
# class PeriodicTable
# 	file = File.read('../lib/periodic_table.json')
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def index
  end
end

app/controllers/lewisdot_controller.rb
class LewisdotController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/metafizzy_controller.rb
class MetafizzyController < ApplicationController
  def index
  end
end

app/controllers/periodictable_controller.rb
class PeriodictableController < ApplicationController
  def index
  end
end

app/controllers/testcenter_controller.rb
class TestcenterController < ApplicationController
  def index
  	answer = Hash.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/lewisdot_helper.rb
module LewisdotHelper
end

app/helpers/metafizzy_helper.rb
module MetafizzyHelper
end

app/helpers/periodictable_helper.rb
module PeriodictableHelper
end

app/helpers/testcenter_helper.rb
module TestcenterHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/experiments/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Tauri' rel='stylesheet' type='text/css'>


<div class="element-container" alt="h">
  <div class="atomic-number">1</div>
  <div class="element-symbol">H</div>
  <div class="element-name">Hydrogen</div>
  <div class="atomic-weight">1.00794</div>
</div>
  
<div class="element-container" alt="he">
  <div class="atomic-number">2</div>
  <div class="element-symbol">He</div>
  <div class="element-name">Helium</div>
  <div class="atomic-weight">4.002602</div>
</div>
  
<div class="element-container">
  <div class="atomic-number">3</div>
  <div class="element-symbol">Li</div>
  <div class="element-name">Lithium</div>
  <div class="atomic-weight">6.941</div>
</div>
<!-- 
<div style="clear:both"></div> -->

<div class="element-container">
  <div class="atomic-number">4</div>
  <div class="element-symbol">Be</div>
  <div class="element-name">Beryllium</div>
  <div class="atomic-weight">9.012182</div>
</div>
  
<div class="element-container">
  <div class="atomic-number">5</div>
  <div class="element-symbol">B</div>
  <div class="element-name">Boron</div>
  <div class="atomic-weight">10.81</div>
</div>
  <div class="element-container">
  <div class="atomic-number">6</div>
  <div class="element-symbol">C</div>
  <div class="element-name">Carbon</div>
  <div class="atomic-weight">12.011</div>
</div>

<!-- <div style="clear:both"></div> -->

  <div class="element-container" alt="n">
  <div class="atomic-number">7</div>
  <div class="element-symbol">N</div>
  <div class="element-name">Nitrogen</div>
  <div class="atomic-weight">14.007</div>
</div>
  <div class="element-container" alt="o">
  <div class="atomic-number">8</div>
  <div class="element-symbol">O</div>
  <div class="element-name">Oxygen</div>
  <div class="atomic-weight">15.999</div>
</div>
<div class="element-container">
  <div class="atomic-number">9</div>
  <div class="element-symbol">F</div>
  <div class="element-name">Fluorine</div>
  <div class="atomic-weight">18.998</div>
</div>
  <div class="element-container">
  <div class="atomic-number">10</div>
  <div class="element-symbol">Ne</div>
  <div class="element-name">Neon</div>
  <div class="atomic-weight">20.180</div>
</div>

<h2>What is the Lewis Dot Structure for OH?</h2>
<p>For demostrative purposes, dropping 'H' and 'O' on their assigned positions will prompt a correct asnwer.</p>
<div class="block">
    <div id="one" class="dotted">H</div> 
    <div id="two" class="dotted">O</div> 
    <div id="three" class="dotted">3</div> 
    <div style="clear:both"></div>
    <div id="four" class="dotted">4</div>
    <div id="5" class="dotted">5</div>
    <div id="6" class="dotted">6</div>
    <div style="clear:both"></div>
    <div id="seven" class="dotted">7</div>
    <div id="eight" class="dotted">8</div>
    <div id="nine" class="dotted">9</div>
</div>
<div id="results">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chemlab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Cabin+Sketch:700' rel='stylesheet' type='text/css'>

  

  <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.0/isotope.pkgd.min.js"></script> -->
  
  
</head>
<body>

  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Home</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
         <li><%= link_to 'Periodic Table', periodictable_path %></li>
         <li><%= link_to 'Molecular Bonding', lewisdot_index_path %></li>
      	
         <!-- <li><%= link_to 'Metafizzy', metafizzy_path %></li> -->
         <li><%= link_to 'Test Center', testcenter_path %></li>
         <li><%= link_to 'Experiments', experiments_index_path %></li>
      </ul>

    </div>
  </nav> 

<%= yield %>

</body>
</html>

app/views/lewisdot/edit.html.erb
<h1>Lewisdot#edit</h1>
<p>Find me in app/views/lewisdot/edit.html.erb</p>

app/views/lewisdot/index.html.erb
<h1>Lewis dot Structure</h1>

<ul class="collapsible" data-collapsible="expandable">
    <li>
      <div class="collapsible-header"><i class="mdi-image-filter-drama"></i>Electron Configuration</div>
      <div class="collapsible-body">
        <p>Lewis Structures are visual representations of the bonds between atoms and illustrate the lone pairs of electrons in molecules. They can also be called Lewis dot diagrams and are used as a simple way to show the configuration of atoms within a molecule.</p>
        <div><%= image_tag 'http://www.middleschoolchemistry.com/img/content/multimedia/chapter_4/lesson_4/covalent_bond_hydrogen_1.jpg', :class => 'himg'%></div>
        <div><%= image_tag 'http://www.middleschoolchemistry.com/img/content/multimedia/chapter_4/lesson_6/covalent_bond_hydrogen_2.jpg', :class => 'himg2' %></div>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-maps-place"></i>Valence Electrons/Ionic and Covalent bonds</div>
      <div class="collapsible-body">
        <p>
          Valence electrons, or the electrons in the outermost electron shell, have an essential role in chemical bonding.
          Ionic bonds are formed between atoms when electrons are transferred from one atom to another. Ionic bond is a bond between nonmetals and metals .
          Covalent bonds are formed between atoms when pairs of electrons are shared between atoms. A covalent bond is between two nonmetals.
          Electrons are transferred/shared so that each atom may reach a more stable electron configuration i.e. the noble gas configuration which contains 8 valence electrons. This is called octet rule.
        </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-social-whatshot"></i>Reading the Periodic Table</div>
      <div class="collapsible-body">
        <div class="wrapper">
          <ul class="main">

            <p>The arrangement of the periodic table is grouped in many ways, one of which shows how many valence electrons are on the outer most shell of an element.</p>
            <!-- Valence E' -->

            <li class="empty">I</li>
            <li class="empty">II</li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty">III</li>
            <li class="empty">IV</li>
            <li class="empty">V</li>
            
            <li class="empty">VI</li>
            <li class="empty">VII</li>
            <li class="empty">VIII</li>
            <!-- ROW 1 -->

            <li data-pos="1" data-nb="1.0079" class="type-1 cat-2">H<span>Hydrogen</span></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li data-pos="2" data-nb="4.0026" class="type-2 cat-2">He<span>Helium</span></li>
            
            <!-- ROW 2 -->
            
            <li data-pos="3" data-nb="6.941" class="type-3 cat-0">Li<span>Lithium</span></li>
            <li data-pos="4" data-nb="9.0122" class="type-4 cat-0">Be<span>Beryllium</span></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li data-pos="5" data-nb="10.811" class="type-5 cat-0">B<span>Boron</span></li>
            <li data-pos="6" data-nb="12.011" class="type-5 cat-0">C<span>Carbon</span></li>
            <li data-pos="7" data-nb="14.007" class="type-5 cat-2">N<span>Nitrogen</span></li>
            
            <li data-pos="8" data-nb="15.999" class="type-5 cat-2">O<span>Oxygen</span></li>
            <li data-pos="9" data-nb="18.998" class="type-5 cat-2">F<span>Fluorine</span></li>
            <li data-pos="10" data-nb="20.180" class="type-2 cat-2">Ne<span>Neon</span></li>
            
            <!-- ROW 3 -->
            
            <li data-pos="11" data-nb="22.990" class="type-3 cat-0">Na<span>Sodium</span></li>
            <li data-pos="12" data-nb="24.305" class="type-4 cat-0">Mg<span>Magnesium</span></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            <li class="empty"></li>
            
            <li class="empty"></li>
            <li class="empty"></li>
            <li data-pos="13" data-nb="26.982" class="type-7 cat-0">Al<span>Aluminium</span></li>
            <li data-pos="14" data-nb="28.086" class="type-5 cat-0">Si<span>Silicon</span></li>
            <li data-pos="15" data-nb="30.974" class="type-5 cat-0">P<span>Phosphorus</span></li>
            
            <li data-pos="16" data-nb="32.065" class="type-5 cat-0">S<span>Sulfur</span></li>
            <li data-pos="17" data-nb="35.453" class="type-5 cat-2">Cl<span>Chlorine</span></li>
            <li data-pos="18" data-nb="39.948" class="type-2 cat-2">Ar<span>Argon</span></li>
            
            <!-- ROW 4 -->
            
            <li data-pos="19" data-nb="39.098" class="type-3 cat-0">K<span>Potassium</span></li>
            <li data-pos="20" data-nb="40.078" class="type-4 cat-0">Ca<span>Calcium</span></li>
            <li data-pos="21" data-nb="44.956" class="type-6 cat-0">Sc<span>Scandium</span></li>
            <li data-pos="22" data-nb="47.867" class="type-6 cat-0">Ti<span>Titanium</span></li>
            <li data-pos="23" data-nb="50.942" class="type-6 cat-0">V<span>Vanadium</span></li>
            
            <li data-pos="24" data-nb="51.996" class="type-6 cat-0">Cr<span>Chromium</span></li>
            <li data-pos="25" data-nb="54.938" class="type-6 cat-0">Mn<span>Manganese</span></li>
            <li data-pos="26" data-nb="55.845" class="type-6 cat-0">Fe<span>Iron</span></li>
            <li data-pos="27" data-nb="58.933" class="type-6 cat-0">Co<span>Cobalt</span></li>
            <li data-pos="28" data-nb="58.693" class="type-6 cat-0">Ni<span>Nickel</span></li>
            
            <li data-pos="29" data-nb="63.546" class="type-6 cat-0">Cu<span>Copper</span></li>
            <li data-pos="30" data-nb="65.39" class="type-7 cat-0">Zn<span>Zinc</span></li>
            <li data-pos="31" data-nb="69.723" class="type-7 cat-0">Ga<span>Gallium</span></li>
            <li data-pos="32" data-nb="72.64" class="type-7 cat-0">Ge<span>Germanium</span></li>
            <li data-pos="33" data-nb="74.922" class="type-5 cat-0">As<span>Arsenic</span></li>
            
            <li data-pos="34" data-nb="78.96" class="type-5 cat-0">Se<span>Selenium</span></li>
            <li data-pos="35" data-nb="79.904" class="type-5 cat-1">Br<span>Bromine</span></li>
            <li data-pos="36" data-nb="83.80" class="type-2 cat-2">Kr<span>Krypton</span></li>
         </ul>
       </div>
     </div>
     </div>
    </li>
</ul>

app/views/lewisdot/new.html.erb
<h1>Lewisdot#new</h1>
<p>Find me in app/views/lewisdot/new.html.erb</p>

app/views/lewisdot/show.html.erb
<h1>Lewisdot#show</h1>
<p>Find me in app/views/lewisdot/show.html.erb</p>

app/views/metafizzy/index.html.erb
<h1>Isotope - filtering &amp; sorting</h1>
<h2>Filter</h2>
<div id="filters" class="button-group">  <button class="button is-checked" data-filter="*">show all</button>
  <button class="button" data-filter=".metal">metal</button>
  <button class="button" data-filter=".transition">transition</button>
  <button class="button" data-filter=".alkali, .alkaline-earth">alkali and alkaline-earth</button>
  <button class="button" data-filter=":not(.transition)">not transition</button>
  <button class="button" data-filter=".metal:not(.transition)">metal but not transition</button>
  <button class="button" data-filter="numberGreaterThan50">number > 50</button>
  <button class="button" data-filter="ium">name ends with &ndash;ium</button>
</div>

<h2>Sort</h2>
<div id="sorts" class="button-group">  <button class="button is-checked" data-sort-by="original-order">original order</button>
  <button class="button" data-sort-by="name">name</button>
  <button class="button" data-sort-by="symbol">symbol</button>
  <button class="button" data-sort-by="number">number</button>
  <button class="button" data-sort-by="weight">weight</button>
  <button class="button" data-sort-by="category">category</button>
</div>


<div id="draggable" class="ui-widget-content" data-category="transition">
  <p>Drag me around</p>
</div>


<div class="isotope">
  <div id="draggable" class="element-item transition metal " data-category="transition">
    <h3 class="name">Mercury</h3>
    <p class="symbol">Hg</p>
    <p class="number">80</p>
    <p class="weight">200.59</p>
  </div>
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Tellurium</h3>
    <p class="symbol">Te</p>
    <p class="number">52</p>
    <p class="weight">127.6</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Bismuth</h3>
    <p class="symbol">Bi</p>
    <p class="number">83</p>
    <p class="weight">208.980</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Lead</h3>
    <p class="symbol">Pb</p>
    <p class="number">82</p>
    <p class="weight">207.2</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Gold</h3>
    <p class="symbol">Au</p>
    <p class="number">79</p>
    <p class="weight">196.967</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Potassium</h3>
    <p class="symbol">K</p>
    <p class="number">19</p>
    <p class="weight">39.0983</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Sodium</h3>
    <p class="symbol">Na</p>
    <p class="number">11</p>
    <p class="weight">22.99</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cadmium</h3>
    <p class="symbol">Cd</p>
    <p class="number">48</p>
    <p class="weight">112.411</p>
  </div>
  <div class="element-item alkaline-earth metal " data-category="alkaline-earth">
    <h3 class="name">Calcium</h3>
    <p class="symbol">Ca</p>
    <p class="number">20</p>
    <p class="weight">40.078</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Rhenium</h3>
    <p class="symbol">Re</p>
    <p class="number">75</p>
    <p class="weight">186.207</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Thallium</h3>
    <p class="symbol">Tl</p>
    <p class="number">81</p>
    <p class="weight">204.383</p>
  </div>
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Antimony</h3>
    <p class="symbol">Sb</p>
    <p class="number">51</p>
    <p class="weight">121.76</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cobalt</h3>
    <p class="symbol">Co</p>
    <p class="number">27</p>
    <p class="weight">58.933</p>
  </div>
  <div class="element-item lanthanoid metal inner-transition " data-category="lanthanoid">
    <h3 class="name">Ytterbium</h3>
    <p class="symbol">Yb</p>
    <p class="number">70</p>
    <p class="weight">173.054</p>
  </div>
  <div class="element-item noble-gas nonmetal " data-category="noble-gas">
    <h3 class="name">Argon</h3>
    <p class="symbol">Ar</p>
    <p class="number">18</p>
    <p class="weight">39.948</p>
  </div>
  <div class="element-item diatomic nonmetal " data-category="diatomic">
    <h3 class="name">Nitrogen</h3>
    <p class="symbol">N</p>
    <p class="number">7</p>
    <p class="weight">14.007</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Uranium</h3>
    <p class="symbol">U</p>
    <p class="number">92</p>
    <p class="weight">238.029</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Plutonium</h3>
    <p class="symbol">Pu</p>
    <p class="number">94</p>
    <p class="weight">(244)</p>
  </div>
</div>

app/views/testcenter/index.html.erb
<h1>Testcenter</h1>

<div style="float:left">
    <div id="hydrogen" class="square"><h4>H</h4></div>
    <div id="oxygen" class="square"><h4>O</h4></div>
    <div id="hydrogen2" class="square"><h4>H</h4></div>
    <!-- <div style="clear:both"></div>
    <div class="square">4</div>
    <div class="square">5</div>
    <div class="square">6</div>
    <div style="clear:both"></div>
    <div class="square">7</div>
    <div class="square">8</div>
    <div class="square">9</div> -->
</div>
<div style="float:left;margin-left:50px;">
    <div id="one" class="squaredotted"><p>1</p></div> 
    <div id="two" class="squaredotted"><p>2</p></div> 
    <div id="three" class="squaredotted">3</div> 
    <div style="clear:both"></div>
    <div id="four" class="squaredotted"><p>4</p></div>
    <div id="five" class="squaredotted"><p>5</p></div>
    <div id="six" class="squaredotted"><p>6</p></div>
    <div style="clear:both"></div>
    <div id="droppable" class="squaredotted">7</div>
    <div id="droppable" class="squaredotted">8</div>
    <div id="droppable"class="squaredotted">9</div>
</div>

app/views/welcome/index.html.erb
<div id="beaker">
  <h1>ChemLab</h1>

  <span class="bubble">
    <span class="glow"> </span>
  </span>

  <span class="bubble2">
    <span class="glow"> </span>
  </span>

  <div id="image">
    <%= image_tag("beaker.png", :alt => "beaker feed") %>
  </div>

</div>